# Generated by Django 5.0 on 2024-01-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_savat_savatitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='umumiy_summa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
