# Generated by Django 5.0 on 2024-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_savat_umumiy_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='savatitem',
            name='summa',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
