# Generated by Django 5.0 on 2024-01-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_savatitem_summa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mahsulot',
            name='janr',
        ),
        migrations.CreateModel(
            name='BannerMahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.bolim'),
        ),
    ]
